from turtle import *
speed(0.00099999)
def yin(radius, color1, color2):
    width(3)
    color("gray", color1)
    begin_fill()
    circle(radius/2., 180)
    circle(radius, 180)
    left(180)
    circle(-radius/2., 180)
    end_fill()
    left(90)
    up()
    forward(radius*0.35)
    right(90)
    down()
    color(color1, color2)
    begin_fill()
    circle(radius*0.15)
    end_fill()
    left(90)
    up()
    backward(radius*0.35)
    down()
    left(90)
    yin(radius/2, "black", "white")

def main():
    reset()
    yin(500, "black", "white")
    yin(500, "white", "black")
    ht()
    return "Done!"

main()
exitonclick()